/** Operator BFF documents — generated from `../server/.../schema.graphql` via `pnpm codegen`. */
export {
  AcceptTriageMutationDocument as ACCEPT_TRIAGE_MUTATION,
  ActivityEventsSubscriptionDocument as ACTIVITY_EVENTS_SUBSCRIPTION,
  ActivityFeedQueryDocument as ACTIVITY_FEED_QUERY,
  DashboardSetupQueryDocument as DASHBOARD_SETUP_QUERY,
  DeclineTriageMutationDocument as DECLINE_TRIAGE_MUTATION,
  DeleteMappingMutationDocument as DELETE_MAPPING_MUTATION,
  EffectiveSettingsQueryDocument as EFFECTIVE_SETTINGS_QUERY,
  GithubFieldsDocument as GITHUB_FIELDS_QUERY,
  IntegrationNavQueryDocument as INTEGRATION_NAV_QUERY,
  MappingsQueryDocument as MAPPINGS_QUERY,
  ReconsiderTriageMutationDocument as RECONSIDER_TRIAGE_MUTATION,
  ReinitIntegrationMutationDocument as REINIT_INTEGRATION_MUTATION,
  TriggerSyncMutationDocument as TRIGGER_SYNC_MUTATION,
  UpdateDestinationSettingsDocument as UPDATE_DESTINATION_SETTINGS_MUTATION,
  UpdateSourceSettingsDocument as UPDATE_SOURCE_SETTINGS_MUTATION,
  UpdateSettingsMutationDocument as UPDATE_SETTINGS_MUTATION,
  UpsertMappingMutationDocument as UPSERT_MAPPING_MUTATION,
  VibeKanbanOrganizationsDocument as VIBE_KANBAN_ORGANIZATIONS_QUERY,
  VibeKanbanProjectsDocument as VIBE_KANBAN_PROJECTS_QUERY,
  VibeKanbanReposDocument as VIBE_KANBAN_REPOS_QUERY,
  VibeKanbanUiStateDocument as VIBE_KANBAN_UI_STATE_QUERY,
} from '../../__generated__/graphql';
